In [29]:
import numpy as np 
import pandas as pd 

In [31]:
# Скалярное произведение
A = np.array([1,2])
B = np.array([4,5])
B @ A # 1*4 + 2*5

14

### Матрицы

### Транспонирование матрицы(переворот)

In [11]:
matrix = np.array([
    [1,2],
    [4,-4],
    [0,17]
])

print('Простая матрица')
print(matrix)
print('Транспониррованная матрица')
print(matrix.T)

Простая матрица
[[ 1  2]
 [ 4 -4]
 [ 0 17]]
Транспониррованная матрица
[[ 1  4  0]
 [ 2 -4 17]]


### Умножение исходной матрицы на вектор длиной 3

In [12]:
vector = [2,1,-1]
print(matrix.T @ vector)
# Умножать надо на транспонированную... разная размерность
# print(np.dot(matrix, vector)) 

[  6 -17]


In [23]:
columns = ['Предмет', 'Плита','Труба','Винт']
data = [
    ['Стул', 0.2, 1.2, 8],
    ['Скамья', 0.5, 0.8, 6],
    ['Стол', 0.8, 1.6, 8]
]
df = pd.DataFrame(data=data, columns=columns)
manufacture = df[['Плита','Труба','Винт']].to_numpy()
# Сколько надо произвести
furniture = [60, 4, 16] 
manufacture.T @ furniture


array([ 26.8, 100.8, 632. ])

### Матричное умножение

Строиться третья матрица  
$C_{ij} = (A_i,B_j)$
- Матрица состоит из скалярных произведений строк первой матрицы на столбцы второй
- Умножение возможно если ширина первой матрицы $А(m*n)$ равна высоте второй матрицы $В (n*r)$ 
- Получиться матрица m*r (размерность n схлопываеться)
- Зависит от порядка умножения!

In [32]:
A = np.array([
    [1, 2, 3], 
    [-1, -2, -3]])

B = np.array([
    [1, 0], 
    [0, 1],
    [1, 1]])
print(A @ B)
print(B @ A)

[[ 4  5]
 [-4 -5]]
[[ 1  2  3]
 [-1 -2 -3]
 [ 0  0  0]]


In [33]:
square_matrix = np.array([
    [1, 2, 3], 
    [-1, -2, -3],
    [0, 0, 0]])

print(square_matrix @ square_matrix)

[[-1 -2 -3]
 [ 1  2  3]
 [ 0  0  0]]


In [2]:
import numpy  as np
import pandas as pd

materials_names = ['Древесная плита', 'Металлическая труба', 'Винты']
venues_names = ['Кофейня', 'Бистро', 'Ресторан']

# матрица, где по строкам указана мебель, а по столбцам — материалы для её изготовления
manufacture = np.array([
    [0.2, 1.2, 8],
    [0.5, 0.8, 6],
    [0.8, 1.6, 8]])

# матрица, где по строкам указаны заведения, а по столбцам — виды мебели
furniture = np.array([
    [12, 0, 3],
    [40, 2, 10],
    [60, 6, 18]])

venues_materials = furniture @ manufacture

print('По заведениям')
print(pd.DataFrame(venues_materials, index=venues_names, columns=materials_names))
print()

venues = np.array([18, 12, 7])

total_materials = venues_materials @ venues

print('Всего')
print(pd.DataFrame([total_materials], index=[''], columns=materials_names))

По заведениям
          Древесная плита  Металлическая труба  Винты
Кофейня               4.8                 19.2  120.0
Бистро               17.0                 65.6  412.0
Ресторан             29.4                105.6  660.0

Всего
  Древесная плита  Металлическая труба   Винты
           1156.8               3977.2  6416.4


### Обратная матрица 

**Единичная матрица** 
$
    E = \begin{pmatrix} 1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & 1 
    \end{pmatrix}
$  
Любая матрица A при умножение на единичную, дает саму себя:   
$AE=EA=A$   

**Обратная для квадратной матрицы**   
$AA^{-1} = A^{-1}A = E$   
Квадратный матрицы для которых можно натйи обратные: называются обратимыми, но не у каждой матрицы есть обратная... 

Для поиска обратной матрицы:  
```python 
np.random.normal()
```

In [15]:
E = np.matrix([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])
E * 1  
np.zeros(len(E))

[0, 0, 0]

In [55]:
import numpy as np
import pandas as pd
from sklearn.metrics import r2_score

columns = ['комнаты', 'площадь', 'кухня', 'пл. жилая', 'этаж', 'всего этажей', 'цена']

data = pd.DataFrame([
    [1, 38.5, 6.9, 18.9, 3, 5, 4200000],
    [1, 38.0, 8.5, 19.2, 9, 17, 3500000],
    [1, 34.7, 10.3, 19.8, 1, 9, 5100000],
    [1, 45.9, 11.1, 17.5, 11, 23, 6300000],
    [1, 42.4, 10.0, 19.9, 6, 14, 5900000],
    [1, 46.0, 10.2, 20.5, 3, 12, 8100000],
    [2, 77.7, 13.2, 39.3, 3, 17, 7400000],
    [2, 69.8, 11.1, 31.4, 12, 23, 7200000],
    [2, 78.2, 19.4, 33.2, 4, 9, 6800000],
    [2, 55.5, 7.8, 29.6, 1, 25, 9300000],
    [2, 74.3, 16.0, 34.2, 14, 17, 10600000],
    [2, 78.3, 12.3, 42.6, 23, 23, 8500000],
    [2, 74.0, 18.1, 49.0, 8, 9, 6000000],
    [2, 91.4, 20.1, 60.4, 2, 10, 7200000],
    [3, 85.0, 17.8, 56.1, 14, 14, 12500000],
    [3, 79.8, 9.8, 44.8, 9, 10, 13200000],
    [3, 72.0, 10.2, 37.3, 7, 9, 15100000],
    [3, 95.3, 11.0, 51.5, 15, 23, 9800000],
    [3, 69.3, 8.5, 39.3, 4, 9, 11400000],
    [3, 89.8, 11.2, 58.2, 24, 25, 16300000],
], columns=columns)

features = data.drop('цена', axis=1)
target = data['цена']

In [57]:
len(features.columns)

6

In [66]:
np.zeros(features.shape[1])

array([0., 0., 0., 0., 0., 0.])

In [71]:
target.mean()

8720000.0

In [79]:

class LinearRegression:
    def fit(self, train_features, train_target):
        X = np.concatenate((np.ones((train_features.shape[0], 1)), train_features), axis=1)
        y = train_target
        w = (np.linalg.inv(X.T @ X) @ X.T) @ y 
        self.w = w[1:]
        self.w0 = w[0]

    def predict(self, test_features):
        return test_features.dot(self.w) + self.w0
    
model = LinearRegression()
model.fit(features, target)
predictions = model.predict(features)
print(r2_score(target, predictions))

0.7781189439686584


In [20]:
np.zeros(len(E))

array([0., 0., 0.])

In [45]:
def MSE(features, predict):
    if len(features) != len(predict):
        raise Exception('len(features) must be equal len(predict)')
    return np.mean(np.square(features - predict))


def get_r2(x, y):
    slope, intercept = np.polyfit(x, y, 1)
    r_squared = 1 - (sum((y - (slope * x + intercept))**2) / ((len(y) - 1) * np.var(y, ddof=1)))
    return r_squared


MSE(np.array([1,2,5]),np.array([1,2,5]))
get_r2(np.array([1,2,5]),np.array([1,2,5]))

1.0

In [33]:
a = np.array([1,2,3])
b = np.array([2,3,4])

In [ ]:
[1,2,3,4,5]

In [47]:
np.mean(E)

0.3333333333333333